[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.2"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = false
